import { describe, expect, it } from 'vitest';
import {
  cookieMatchesHost,
  formatNetscapeCookieLine,
  parseServerArgs,
  planExtraction,
  toNetscapeCookieFile,
} from '../../src/extract-sap-cookies.ts';

describe('extract-sap-cookies pure helpers', () => {
  it('parses server args with CLI URL taking precedence over env URL', () => {
    const parsed = parseServerArgs(['--url', 'https://cli.example'], {
      SAP_URL: 'https://env.example',
      SAP_COOKIE_FILE: '/tmp/env-cookies.txt',
    });

    expect(parsed.url).toBe('https://cli.example');
    expect(parsed.cookieFile).toBe('/tmp/env-cookies.txt');
  });

  it('rejects unsupported browser names before resolving a browser binary', () => {
    expect(() =>
      planExtraction({
        args: ['--url', 'http://sapdev:50000', '--browser', 'safari'],
        env: {},
        cwd: process.cwd(),
        platform: 'linux',
      }),
    ).toThrow("Unsupported --browser value 'safari'");
  });

  it('matches exact host and subdomain cookies, but not unrelated domains', () => {
    expect(cookieMatchesHost('sap.example.com', 'sap.example.com')).toBe(true);
    expect(cookieMatchesHost('.example.com', 'sap.example.com')).toBe(true);
    expect(cookieMatchesHost('example.com', 'notexample.com')).toBe(false);
  });

  it('formats one cookie as a Netscape cookie line', () => {
    const line = formatNetscapeCookieLine({
      domain: '.example.com',
      path: '/sap',
      secure: true,
      expires: 1234.9,
      name: 'MYSAPSSO2',
      value: 'token',
    });

    expect(line).toBe('.example.com\tTRUE\t/sap\tTRUE\t1234\tMYSAPSSO2\ttoken');
  });

  it('renders a complete Netscape cookie file', () => {
    const text = toNetscapeCookieFile([
      {
        domain: 'sap.example.com',
        path: '/',
        secure: false,
        expires: 0,
        name: 'sap-contextid',
        value: 'abc',
      },
    ]);

    expect(text).toContain('# Netscape HTTP Cookie File\n');
    expect(text).toContain('# Generated by ARC-1 extract-sap-cookies.ts\n');
    expect(text).toContain('sap.example.com\tFALSE\t/\tFALSE\t0\tsap-contextid\tabc\n');
  });
});

describe('extract-sap-cookies planExtraction', () => {
  it('refuses to run when SAP_PP_ENABLED=true', () => {
    expect(() =>
      planExtraction({
        args: ['--url', 'http://sapdev:50000'],
        env: { SAP_PP_ENABLED: 'true' },
        cwd: process.cwd(),
        platform: process.platform,
      }),
    ).toThrow('SAP_PP_ENABLED=true');
  });
});
